<a href="https://colab.research.google.com/github/junxnone/examples/blob/master/pytorch/tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 如何使用 GPU 
- 选择 Runtime -> Change Runtime type
- hardward accelerator 选择 GPU

    


# 安装 pytorch and torchvision


In [1]:
!pip3 install https://download.pytorch.org/whl/cu80/torch-1.0.0-cp36-cp36m-linux_x86_64.whl
!pip3 install torchvision

     |████████████████████████████████| 532.5MB 30kB/s 
ERROR: torchvision 0.4.2 has requirement torch==1.3.1, but you'll have torch 1.0.0 which is incompatible.
  Found existing installation: torch 1.3.1
    Uninstalling torch-1.3.1:
      Successfully uninstalled torch-1.3.1
     |████████████████████████████████| 734.6MB 23kB/s 
  Found existing installation: torch 1.0.0
    Uninstalling torch-1.0.0:
      Successfully uninstalled torch-1.0.0


In [0]:
%matplotlib inline


 PyTorch 是什么?
================

一个基于 Python 的科学计算包，适用于以下两种情况：

-  想要替换 numpy 以利用 GPU 的算力
-  需要一个高灵活性，速度快的深度学习框架

> 早期大家用 numpy 搭建网络,只能使用 CPU，要想使用 GPU 只能用其他 package 替换

Getting Started
---------------

## Tensors

Tensors 类似于 NumPy 的 ndarrays, 区别是 Tensors 可以使用 GPU 加速。



In [0]:
from __future__ import print_function
import torch

创建一个未初始化的矩阵:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[2.8019e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 2.3592e-16]])


创建一个随机初始化的矩阵:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8250, 0.0677, 0.2949],
        [0.7364, 0.9256, 0.0218],
        [0.2134, 0.9679, 0.1554],
        [0.4021, 0.6479, 0.2788],
        [0.7190, 0.5107, 0.4980]])


创建一个值为`0`, `dtype` 为 `long`的矩阵:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


创建指定数值的 `tensor`:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


基于一个 `tensor` 创建 `tensor`, 如果未指定 `dtype`，则新 `tensor` 的属性同原 `tensor`



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1901, -0.0409, -0.9711],
        [ 1.5972,  1.0179,  0.4180],
        [-0.5143, -0.5438, -1.9759],
        [ 0.4046, -0.8019, -0.3620],
        [-0.6700, -0.5574,  0.3332]])


获取 `size`:



In [8]:
print(x.size())

torch.Size([5, 3])


**注意:**  `torch.Size` 是一个 `tuple`, 支持 `tuple` 的所有操作。

## 运算
每种运算经常会有多种实现语法，下面是 `加` 操作的实现。

**`加` - 实现一**



In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.4501,  0.2054, -0.7661],
        [ 2.5661,  1.2065,  0.9808],
        [-0.2271,  0.0249, -1.8873],
        [ 0.5043, -0.6670, -0.3279],
        [-0.1753, -0.0233,  0.6322]])


**`加` - 实现二**



In [10]:
print(torch.add(x, y))

tensor([[ 0.4501,  0.2054, -0.7661],
        [ 2.5661,  1.2065,  0.9808],
        [-0.2271,  0.0249, -1.8873],
        [ 0.5043, -0.6670, -0.3279],
        [-0.1753, -0.0233,  0.6322]])


**`加` - 实现三 - 指定输出 `tensor`**



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.4501,  0.2054, -0.7661],
        [ 2.5661,  1.2065,  0.9808],
        [-0.2271,  0.0249, -1.8873],
        [ 0.5043, -0.6670, -0.3279],
        [-0.1753, -0.0233,  0.6322]])


**`加` - 实现四 - 替换原值**



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.4501,  0.2054, -0.7661],
        [ 2.5661,  1.2065,  0.9808],
        [-0.2271,  0.0249, -1.8873],
        [ 0.5043, -0.6670, -0.3279],
        [-0.1753, -0.0233,  0.6322]])


**注意:** 任何 `in-place` 替换原值的计算都是使用后缀 `_`.  
 如下操作都将改变 `x` 值: 
 - ``x.copy_(y)``
 - ``x.t_()``

可以像 `Numpy` 似的使用 `index` 索引操作!



In [13]:
print(x[:, 1])

tensor([-0.0409,  1.0179, -0.5438, -0.8019, -0.5574])


Resizing: 如果想 `resize/reshape tensor`, 可以使用 ``torch.view``:



In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果是包含一个元素的 `tensor`, 可以使用 `.item()` 方法获取值.



In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.9805])
-1.9805296659469604


**扩展阅读:**


  100+ 种 `Tensor` 操作, 包括 `transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers`... 等等, 参见[文档](https://pytorch.org/docs/torch).

与 `NumPy` 并用
------------

 `Torch Tensor` 和 `NumPy array` 转换很容易.

转换后的 `Torch Tensor` 和 `NumPy array` 会共享内存(指向同一个位置), 当一个值改变时，另一个也会改变.

## `Torch Tensor` 转 `NumPy Array`


In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


改变 `Tensor`, `Array` 也会改变.





In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## `NumPy Array` 转 `Torch Tensor`
改变 `np array`, 也会自动改变 `Torch Tensor`




In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


所有 CPU 上的 `Tensor` 都可以与 `NumPy` 互相转换, CharTensor 除外.

CUDA Tensors
------------

Tensors 可以使用 `.to` 方法移动到不同的 `device`上.



In [20]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([-0.9805], device='cuda:0')
tensor([-0.9805], dtype=torch.float64)
